[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
miette = { version = "7.2.0", features = ["fancy"] }
core = { path = "../core" }
